EDUCATIONAL_VIDEOS = [
    ("L8IzQ7q6Xd8", "Swing Trading For Beginners"),
    ("h-xDKCjEv0c", "Day Trading For Beginners Stock Market 101"),
    ("sFYOKIsPdes", "Options Trading For Beginners Step-by-Step"),
    ("vSVLc5Q_R9A", "3 Bar Play How To Use"),
    ("MK2V6GKBmf0", "3 Powerful Swing Trading Strategies"),
    ("dkapAHR9oqk", "How To GROW A Small Account in 2020 Beginner Trading"),
    ("6xss-gjBCzA", "Webull Correct Way To Use This Powerful Broker"),
    ("ysscG84aDok", "Indicators That Actually Work For Trading"),
    ("P3oXSKZXfXA", "When To Buy Stocks Exact Point"),
    ("kU5qBzKtRKQ", "When To Sell Stocks Exact Point"),
    ("TYGsqobuz44", "Confirmation How To Buy At Most Powerful Entry Point"),
    ("iQPU1Pyic4U", "VWAP Indicator Tips and Tricks for Trading Stocks"),
    ("bMIf0Ws5ds0", "When To Enter Swing Trades Profitably"),
    ("GHG3Kf-FYvw", "3 Criteria for Finding Swing Stocks"),
    ("4WPE-MGgyr4", "Trader Taxes Your Guidebook To Paying LESS"),
    ("tHtovnCY6uY", "1 Free Stock Scanner FINVIZ"),
    ("cfHWea-Rrl8", "RSI Trading Most Powerful Way To Trade With RSI Indicator"),
    ("-LkJ7ykGpEI", "How To Day Trade Penny Stocks For Beginners"),
    ("ipHPp5SEosE", "Set Up Top Indicators in ThinkorSwim Step-by-Step"),
    ("uO4yJGSz1vU", "How To Spot A Stock Reversal BEFORE It Happens"),
    ("vkQzEEGqGxs", "Stop Loss Scam How To Avoid and Alternatives"),
    ("Y9tkyYnncvM", "Level 2 How To Read Real-Time Quotes"),
    ("wmKnPOG7cT8", "Leveraged ETFs Step-by-Step for Beginners"),
    ("o3gbEYlcViI", "3 Bar Play How To Trade For Beginners"),
    ("bQT7R5hQfns", "MACD Indicator How To Use For Trading Stocks"),
    ("wkykR4ct_NM", "How To Scan For The Best Stocks"),
    ("fb5dWLkPucM", "3 Options Trading Proven Strategies for Beginners"),
    ("QYo8m9o6N_g", "Volume How To Use When Trading"),
    ("H1XbtWdhZ5E", "Stock Market For Beginners 2022 FOR SMALL ACCOUNTS"),
    ("eayLV2ZBmEA", "How To Spot Winning Stocks using ThinkorSwim"),
    ("bpMVJtB16Fc", "How To Trade Stocks For Beginners Five Working Strategies 2024"),
    ("hf1BMcDp9EU", "Natural Gas How To Trade in 2020 UGAZ DGAZ"),
    ("6ya2G_4DDNQ", "Earnings Reports How To Find and Trade Winners"),
    ("9iGfgajluP8", "1 Moving Average Crossover Strategy"),
    ("2VQp6-alQMg", "Short Selling What It Is and How To Do It"),
    ("qm1ONfiT_lg", "Trade Alerts How To Set INDICATOR Alerts on ThinkorSwim"),
    ("WMRDuAdk7q4", "How To Avoid FALSE Breakouts"),
    ("ANGeuB0fQcs", "5 Criteria For Penny Stocks BEFORE Spike"),
    ("amWa_YQPeak", "How To Pick and Trade Multiple Time Frames"),
    ("TdPVJO--aus", "When To Exit Swing Positions Profitably"),
    ("EsB4m6v0RpM", "Ichimoku Cloud How To Step Up Your Trading"),
    ("cLFLUzjsODo", "Natural Gas How To Trade in 2019 UGAZ DGAZ"),
    ("xIAWXZm1LoI", "Bollinger Bands What They Are and How To USE Them"),
    ("O-bxw9p5N5c", "When To Lock In Profits Swing Trading 101"),
    ("u_h1nT8lkEo", "When To Let Winners RUN Day Trading"),
    ("G_ImDM9XekI", "Top Marijuana Stocks How To Find and Trade in 2019"),
]